### ISSUE TITLE
Wrong task's state 

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/0-robot#138]
I created 2 vms on OVC both of them were running but i got different tasks states. One task was error and the other was ok 

![image2](https://user-images.githubusercontent.com/15011431/37598472-f69f4156-2b8a-11e8-8548-0be39e9b0bfd.png)

![image1](https://user-images.githubusercontent.com/15011431/37598457-ec3f4c92-2b8a-11e8-9218-33e86cf577dd.png)

**Comment by zaibon** [comment]
in the task in state error, you can inspect the error condition with `task.eco.printTraceback()` so you have an idea what went wrong

**Comment by john-kheir** [comment]
I will try it again and try to print an error

**Comment by john-kheir** [comment]
- **That's one error i got in which the task state is error however the vm is deployed and running .. but this error is not relevant to zrobot anymore**

## task.eco.printTraceback()
```
Traceback (most recent call last):
  File "/root/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self.func()
  File "/opt/code/github/openvcloud/0-templates/templates/node/node.py", line 131, in install
    machine = self._machine_create()
  File "/opt/code/github/openvcloud/0-templates/templates/node/node.py", line 156, in _machine_create
    managed_private=self.data.get('managedPrivate', False)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Space.py", line 295, in machine_create
    machine.authorizeSSH(sshkeyname=sshkeyname)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Machine.py", line 312, in authorizeSSH
    self._authorize(sshkeyname, instance, addr, port, None)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Machine.py", line 328, in _authorize
    sshclient.ssh_authorize(key=sshkeyname, user='root')
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 159, in ssh_authorize
    sshkey = j.clients.sshkey.get(key)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/JSBaseClassConfigs.py", line 43, in get
    return self._child_class(instance=instance, data=data, parent=self, interactive=interactive)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/sshkey/SSHKey.py", line 23, in __init__
    parent=parent, template=TEMPLATE, interactive=interactive)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/JSBaseClassConfig.py", line 30, in __init__
    self, instance=self._instance, data=data, template=self._template, ui=self._ui)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 222, in _get_for_obj
    sc = Config(instance=instance, location=location, template=template, data=data)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/Config.py", line 24, in __init__
    if not j.sal.fs.exists(self.path):
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/Config.py", line 63, in path
    self._path = j.sal.fs.joinPaths(j.tools.configmanager.path, self.location, self.instance + '.toml')
TypeError: unsupported operand type(s) for +: 'int' and 'str'

```
