### ISSUE TITLE
ContextualVersionConflict when starting 0-robot

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/0-robot#139]
When starting zrobot I got this:
```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Jinja2 2.8 (/usr/local/lib/python3.5/dist-packages), Requirement.parse('Jinja2>=2.9.6'), {'JumpScale9Lib'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/zrobot", line 4, in <module>
    __import__('pkg_resources').require('ZeroRobot==0.0.1')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Jinja2 2.8 (/usr/local/lib/python3.5/dist-packages), Requirement.parse('Jinja2>=2.9.6'), {'JumpScale9Lib'})
root@vm-2114:/opt/code/github/jumpscale/0-robot# pip3 install Jinja
Collecting Jinja
  Downloading Jinja-1.2.tar.gz (252kB)
    100% |################################| 256kB 2.5MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dxe0v92i/Jinja/setup.py", line 28
        except DistutilsError, e:
                             ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dxe0v92i/Jinja/
root@vm-2114:/opt/code/github/jumpscale/0-robot# pip3 install Jinja2
Requirement already satisfied: Jinja2 in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: MarkupSafe in /usr/lib/python3/dist-packages (from Jinja2)
root@vm-2114:/opt/code/github/jumpscale/0-robot# pip3 install Jinja
Collecting Jinja
  Using cached Jinja-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-y6s31kib/Jinja/setup.py", line 28
        except DistutilsError, e:
                             ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-y6s31kib/Jinja/
root@vm-2114:/opt/code/github/jumpscale/0-robot# pip3 update Jinja
ERROR: unknown command "update"
root@vm-2114:/opt/code/github/jumpscale/0-robot# pip3 remove Jinja
ERROR: unknown command "remove"
root@vm-2114:/opt/code/github/jumpscale/0-robot# pip3 uninstall Jinja
Cannot uninstall requirement Jinja, not installed
root@vm-2114:/opt/code/github/jumpscale/0-robot# pip3 uninstall jinja
Cannot uninstall requirement jinja, not installed
root@vm-2114:/opt/code/github/jumpscale/0-robot# pip3 install Jinja
Collecting Jinja
  Using cached Jinja-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-19pwnoct/Jinja/setup.py", line 28
        except DistutilsError, e:
                             ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-19pwnoct/Jinja/
```

**Comment by yveskerwyn** [comment]
I had first to uninstall Jinja2-2.8 and then reinstall Jinja2 => Jinja2-2.10:

```bash
pip3 uninstall Jinja2
pip3 install Jinja2
```
