### ISSUE TITLE
Restarting robot fails with `Connection Refused` error

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/0-robot#51]
It seems there is some kind of a race condition when the 0-robot is trying to access its own internal API. This only happens when the data repository is already populated. 

```python
raceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=6600): Max retries exceeded with url: /services?name=main&template_uid=github.com%2Fopenvcloud%2F0-templates%2Fsshkey%2F0.0.1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7711ef8f98>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/zrobot", line 25, in <module>
    entry_point()
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/cli/server.py", line 36, in start
    robot.start(listen=listen)
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/robot.py", line 84, in start
    self._load_services()
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/robot.py", line 141, in _load_services
    srv = scol.load(tmplClass, srv_dir)
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/service_collection.py", line 83, in load
    srv = template(name=service_info['name'], guid=service_info['guid'], data=service_data)
  File "/opt/code/github/openvcloud/0-templates/templates/openvcloud/openvcloud.py", line 13, in __init__
    sshkey_path = self._validate_data()
  File "/opt/code/github/openvcloud/0-templates/templates/openvcloud/openvcloud.py", line 36, in _validate_data
    ssh_keys = self.api.services.find(template_uid=SSHKEY_TEMPLATE, name=self.data.get('sshkey', None))
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/dsl/ZeroRobotAPI.py", line 70, in find
    for service in robot.services.find(**kwargs):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/dsl/ZeroRobotManager.py", line 98, in find
    services, _ = self._client.api.services.listServices(query_params=kwargs)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zerorobot/client/services_service.py", line 160, in listServices
    resp = self.client.get(uri, None, headers, query_params, content_type)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zerorobot/client/http_client.py", line 67, in get
    return self._handle_data(uri, data, headers, params, content_type, self.session.get)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zerorobot/client/http_client.py", line 49, in _handle_data
    res = method(uri, headers=headers, params=params)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6600): Max retries exceeded with url: /services?name=main&template_uid=github.com%2Fopenvcloud%2F0-templates%2Fsshkey%2F0.0.1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7711ef8f98>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPConnectionPool(host='localhost', port=6600): Max retries exceeded with url: /services?name=main&template_uid=github.com%2Fopenvcloud%2F0-templates%2Fsshkey%2F0.0.1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7711ef8f98>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

This exception happens when I stop the robot and then start it again.

**Comment by muhamadazmy** [comment]
Is it illegal to find a service via name, and/or template_uid in the template `__init__` method ?

**Comment by zaibon** [comment]
Ok so it's indeed a problem in the way we start the robot.
Bootsrap flow is the followin:
- loading templates from filesystem
- loading/starting existing services
- start listening http requests

So if a service tries to access the api in it's __init__method we'll get this error

**Comment by zaibon** [comment]
After some disscusion with @muhamadazmy here is what we found:

In order to allow call to `self.api` from the `__init__` method of the services we need to change the bootstrap flow of the robot. Now it will be:
- loading templates from filesystem
- start listening http requests
- load all services from filesystem
- call `validate` method on all the services
