### ISSUE TITLE
parsing of blueprint fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/0-robot#96]
Executing this blueprint:
```yaml
services:
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__main:
        description: test
```

Result:
```python
Traceback (most recent call last):
  File "/usr/local/bin/zrobot", line 25, in <module>
    entry_point()
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/cli/blueprint.py", line 37, in execute
    msg = err.response.json()['message']
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
```

**Comment by yveskerwyn** [comment]
It turned out not to be related to the blueprint, as was shown in the log:
```python
ImportError: No module named 'ipdb
```

**Comment by zaibon** [comment]
Ok, so that as human error, but still you should have received a proper error message.
